name: ZARN SAST

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  schedule:
    - cron: '28 23 * * 1'

jobs:
  zarn:
    name: Security Static Analysis with ZARN
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      
    - name: Perform Static Analysis
      uses: htrgouvea/zarn@0.0.9

    - name: Send result to Github Security
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: result.sarif
